// src/app/join-room/page.tsx
'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { useAuth } from '@/contexts/AuthContext'
import { createClient } from '@/lib/supabase/client'
import Link from 'next/link'

export default function JoinRoom() {
  const router = useRouter()
  const { user } = useAuth()
  const supabase = createClient()

  const [roomCode, setRoomCode] = useState('')
  const [joining, setJoining] = useState(false)
  const [error, setError] = useState('')

  const handleJoinRoom = async (e: React.FormEvent) => {
    e.preventDefault()
    
    if (!user) {
      setError('You must be signed in to join a room')
      return
    }

    if (roomCode.length !== 6) {
      setError('Room code must be 6 characters')
      return
    }

    setJoining(true)
    setError('')

    try {
      // Check if room exists
      const { data: room, error: roomError } = await supabase
        .from('rooms')
        .select('*, room_participants(user_id)')
        .eq('code', roomCode.toUpperCase())
        .single()

      if (roomError || !room) {
        throw new Error('Room not found')
      }

      // Check if room is full
      if (room.room_participants.length >= room.max_players) {
        throw new Error('Room is full')
      }

      // Check if user is already in room
      const alreadyJoined = room.room_participants.some(
        (p: any) => p.user_id === user.id
      )

      if (alreadyJoined) {
        // Just redirect to lobby
        router.push(`/lobby/${room.code}`)
        return
      }

      // Add user as participant
      const { error: participantError } = await supabase
        .from('room_participants')
        .insert({
          room_id: room.id,
          user_id: user.id,
        })

      if (participantError) throw participantError

      // Redirect to lobby
      router.push(`/lobby/${room.code}`)
    } catch (err: any) {
      console.error('Error joining room:', err)
      setError(err.message || 'Failed to join room')
      setJoining(false)
    }
  }

  if (!user) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 p-8">
        <div className="card text-center">
          <h2 className="text-2xl font-bold mb-4">Sign in Required</h2>
          <p className="text-gray-300 mb-6">You must be signed in to join a room.</p>
          <Link href="/" className="btn-primary inline-block">
            Go Home
          </Link>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 p-8">
      <div className="max-w-2xl mx-auto">
        <Link href="/" className="text-blue-400 hover:text-blue-300 mb-6 inline-block">
          ← Back to Home
        </Link>

        <div className="card">
          <h1 className="text-4xl font-bold mb-8 text-center">🚪 Join Room</h1>

          <form onSubmit={handleJoinRoom} className="space-y-6">
            <div>
              <label className="block text-sm font-semibold mb-2">Room Code</label>
              <input
                type="text"
                value={roomCode}
                onChange={(e) => setRoomCode(e.target.value.toUpperCase())}
                placeholder="Enter 6-character code"
                maxLength={6}
                className="input text-center text-3xl font-mono tracking-widest"
                autoFocus
              />
              <p className="text-gray-400 text-sm mt-2">
                Ask the host for the room code
              </p>
            </div>

            {error && (
              <div className="bg-red-900/50 border border-red-500 text-red-200 px-4 py-3 rounded">
                {error}
              </div>
            )}

            <button
              type="submit"
              disabled={joining || roomCode.length !== 6}
              className="btn-primary w-full text-xl disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {joining ? 'Joining...' : 'Join Room'}
            </button>
          </form>

          <div className="mt-8 text-center text-gray-400">
            <p className="mb-2">Don't have a room code?</p>
            <Link href="/create-room" className="text-blue-400 hover:text-blue-300">
              Create your own room →
            </Link>
          </div>
        </div>
      </div>
    </div>
  )
}

// src/views/JoinRoom.vue
<template>
  <div class="min-h-screen flex items-center justify-center p-4">
    <div class="max-w-md w-full bg-white/10 backdrop-blur-sm rounded-xl p-8">
      <h1 class="text-4xl font-bold mb-8 text-center">Join Room</h1>
      
      <form @submit.prevent="joinRoom" class="space-y-6">
        <div>
          <label class="block text-sm font-medium mb-2">Room Code</label>
          <input 
            v-model="roomCode"
            type="text"
            required
            maxlength="6"
            class="w-full px-4 py-3 rounded-lg bg-white/10 border border-white/20 focus:border-purple-500 focus:outline-none text-2xl text-center uppercase tracking-widest font-bold"
            placeholder="ABC123"
            @input="roomCode = roomCode.toUpperCase()"
          />
          <p class="text-xs text-gray-400 mt-2">Enter the 6-character room code</p>
        </div>

        <button
          type="submit"
          :disabled="loading || roomCode.length !== 6"
          class="w-full bg-pink-600 py-4 rounded-lg font-bold text-lg hover:bg-pink-700 transition disabled:opacity-50"
        >
          {{ loading ? 'Joining...' : 'Join Room' }}
        </button>

        <router-link 
          to="/"
          class="block text-center text-gray-400 hover:text-gray-300"
        >
          Back to Home
        </router-link>
      </form>

      <div v-if="error" class="mt-4 p-4 bg-red-500/20 border border-red-500 rounded-lg">
        {{ error }}
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { supabase } from '@/lib/supabase'

const router = useRouter()

const roomCode = ref('')
const loading = ref(false)
const error = ref('')

const joinRoom = async () => {
  loading.value = true
  error.value = ''
  
  try {
    const { data: { session } } = await supabase.auth.getSession()
    
    // Check if room exists
    const { data: room, error: roomError } = await supabase
      .from('rooms')
      .select('*')
      .eq('code', roomCode.value)
      .single()
    
    if (roomError || !room) {
      error.value = 'Room not found'
      return
    }
    
    if (room.status !== 'WAITING') {
      error.value = 'Room has already started or ended'
      return
    }
    
    // Check current participants count
    const { count } = await supabase
      .from('room_participants')
      .select('*', { count: 'exact', head: true })
      .eq('room_id', room.id)
    
    if (count >= room.max_players) {
      error.value = 'Room is full'
      return
    }
    
    // Check if already joined
    const { data: existing } = await supabase
      .from('room_participants')
      .select('*')
      .eq('room_id', room.id)
      .eq('user_id', session.user.id)
      .single()
    
    if (!existing) {
      // Add participant
      await supabase.from('room_participants').insert({
        room_id: room.id,
        user_id: session.user.id,
        is_host: false
      })
    }
    
    router.push(`/lobby/${roomCode.value}`)
  } catch (err) {
    error.value = 'Error joining room: ' + err.message
  } finally {
    loading.value = false
  }
}
</script>
